Clarify why ipfs file ls is being deprecated.
ipfs/go-ipfs pull request #7755
Opened 2020-11-07 06:55 UTC by ChaituVR

Related to https://github.com/ipfs/ipfs-docs/issues/301

As mentioned in https://discuss.ipfs.io/t/why-is-ipfs-files-ls-being-deprecated/7881/9

2020-11-11 21:46 UTC, Stebalien commented on core/commands/files.go
> +		Tagline: "List directories in the local mutable namespace. (Both IPFS and MFS paths)",
This is a bit much for the tag line.

2020-11-11 21:46 UTC, Stebalien commented on core/commands/files.go
> +List directories in the local mutable namespace (Both IPFS and MFS paths).
Maybe expand this into a full sentence?

2020-11-11 21:46 UTC, Stebalien commented on core/commands/ls.go
> +		Tagline: "List directory contents for Unix filesystem objects. (Only IPFS paths)",
I think this is more likely to confuse than it is to help. Seeing this, my immediate reaction would be "Only IPFS paths? What other paths could this list?"

2020-11-16 12:33 UTC, ChaituVR commented
Thanks @Stebalien, Changed a few things, Please review again and let me know if something can be improved

2020-11-16 18:31 UTC, Stebalien requested changes

2020-11-16 18:31 UTC, Stebalien commented on core/commands/ls.go
> +Displays the contents of an IPFS or IPNS object(s) at the given path, (Won't work with MFS paths - Use 'ipfs files ls' instead) with
I'm still not convinced this helps anyone and I'd rather not introduce a new concept (mfs) here. Did you actually experience confusion expecting `ipfs ls` to list MFS paths?

2020-11-16 18:31 UTC, Stebalien commented on core/commands/files.go
> +List directories in the local mutable namespace (Works on both IPFS and MFS paths).
```suggestion
List directories in the local mutable namespace (works on both IPFS and MFS paths).
```

2020-11-16 18:31 UTC, Stebalien commented on core/commands/unixfs/ls.go
> +		Tagline: "List directory contents for Unix filesystem objects. Deprecated: Use 'ipfs ls' instead",
```suggestion
		Tagline: "List directory contents for Unix filesystem objects. Deprecated: Use 'ipfs ls' instead.",
```

2020-11-16 18:31 UTC, Stebalien commented on core/commands/unixfs/ls.go
>  This functionality is deprecated, and will be removed in future versions. If
Let's try to keep this as concise as possible:

"...in future versions _as it duplicates the functionality of `ipfs ls`_."

We can then drop the other changes.

2020-11-24 08:38 UTC, ChaituVR commented
@Stebalien Changed a few things, now only `ipfs files ls` command  have 
>ipfs files ls works on both IPFS paths and MFS paths.

so for someone looking for MFS paths can find this helpful, and new users may just ignore it has IPFS mentioned

2020-11-24 18:01 UTC, Stebalien approved these changes

2020-11-24 18:40 UTC, merged

2020-11-24 18:41 UTC, aschmahmann commented
Thanks @Stebalien and @ChaituVR