feat support non-ICANN DNS
ipfs/go-ipfs pull request #8071
Opened 2021-04-13 16:03 UTC by mycorrhizas

@lidel 

re [issue](https://github.com/ipfs/go-ipfs/issues/8060)

I switched `IsDomain()` from `jbenet/go-is-domain`  to `IsDomainName` from `github.com/miekg/dns` as suggested.

I had to change one of the tests for everything to pass. This may be an error on my side, but I could not understand why `http://k51qzi5uqu5di608geewp3nqkg0bpujoasmka7ftkyxgcm3fh1aroup0gsdrna.ipns.localhost/` was expected.

2021-04-15 05:49 UTC, Angie3120 requested changes

2021-04-15 05:49 UTC, Angie3120 commented on core/corehttp/hostname.go
> -	isd "github.com/jbenet/go-is-domain"
isd "github.com/jbenet/go-is-domain

2021-04-15 05:49 UTC, Angie3120 requested changes

2021-04-15 05:49 UTC, Angie3120 commented on core/corehttp/hostname.go
> -	isd "github.com/jbenet/go-is-domain"
Just making a hange

2021-04-20 00:39 UTC, lidel requested changes
Thank you @mycorrhizas! 

I think we need to make this smarter and replace `IsDomainName` with a helper function that uses `IsDomainName` internally, but first correctly detects valid PeerID and returns "false" before calling `IsDomainName`. 

Otherwise, we get false-positives when a valid  PeerID is used in subdomain (thats why your test did not pass).

Samples you can use for testing:

- `QmY3hE8xgFCjGcz6PHgnvJz5HZi1BaKRfPkn1ghZUcYMjD` (legacy peerid multihash  in base58btc)
- `12D3KooWFB51PRY9BxcXSH6khFXw1BZeszeLDy7C8GciskqCTZn5` (new peerid multihash in base58btc)
- `k2k4r8l9ja7hkzynavdqup76ou46tnvuaqegbd04a4o1mpbsey0meucb` (new peerid as CIDv1 in base36)

lmk if anything is unclear

2021-04-20 00:39 UTC, lidel commented on core/corehttp/hostname_test.go
> +		{httpRequest, "localhost", "/ipns/12D3KooWFB51PRY9BxcXSH6khFXw1BZeszeLDy7C8GciskqCTZn5", "http://12D3KooWFB51PRY9BxcXSH6khFXw1BZeszeLDy7C8GciskqCTZn5.ipns.localhost/", nil},
This is invalid, case-sensitive identifiers are not allowed in DNS labels, we need to make it work without changing the test:

```suggestion
		{httpRequest, "localhost", "/ipns/12D3KooWFB51PRY9BxcXSH6khFXw1BZeszeLDy7C8GciskqCTZn5", "http://k51qzi5uqu5di608geewp3nqkg0bpujoasmka7ftkyxgcm3fh1aroup0gsdrna.ipns.localhost/", nil},
```

2021-04-20 00:39 UTC, lidel commented on core/corehttp/hostname.go
> +	if _, ok := dns.IsDomainName(rootID); !ok && isPeerIDNamespace(ns) {
This won't work, because IsDomainName(peerIDs) returns false-positive.

2021-04-21 17:49 UTC, lidel commented
Ok, things got a bit more complicated because we have various PRs  in flight, all related to DNS and DNSLink.

I think we need some things to land first, to unblock this PR:

- go-namesys release 
  - with  https://github.com/ipfs/go-namesys/pull/10 and https://github.com/ipfs/go-namesys/pull/12
  - and without `github.com/jbenet/go-is-domain`  https://github.com/ipfs/go-namesys/pull/13
- support for configurable DNS servers (https://github.com/ipfs/go-ipfs/issues/6532)

2021-04-24 09:29 UTC, mycorrhizas commented
@lidel apologies for the late reply 

thanks for explaining and resolving the issue with `isDomainNameAndNotPeerID`?

2021-04-26 22:20 UTC, lidel approved these changes
LGTM, but as I did some work here this needs more eyes.

@aschmahmann as noted during today's  triage, this is ready for your final :eyes: 

FYSA https://github.com/ipfs/go-namesys/pull/13 already landed in namesys, so this is the final piece of the puzzle.
We may want to merge this AFTER https://github.com/ipfs/go-ipfs/pull/8068 as it should be easier to rebase this one if needed, than the other way around.

2021-04-27 18:51 UTC, aschmahmann approved these changes
LGTM, we'll merge after the DoH PR

2021-05-13 17:11 UTC, merged