Fix/gateway: add more debug logs
ipfs/go-ipfs pull request #8105
Opened 2021-05-03 18:47 UTC by sujanasowrirajan

This PR adds more logging at debug level for gateway_handler.go.
Fixes issue #7873 

- Wraps calls to `http.Redirect` in `redirect`, which logs request and status code
- Log errors in method `webErrorWithCode`, which wraps calls to `http.Error`
- Replaced all usages of `http.Error` with `webError`
- Added couple of log lines for when CID is mapped or file is served

2021-05-10 19:50 UTC, Stebalien requested changes
Thanks!

Please prefer structured logging where possible. E.g., `log.Debugw("redirected", "from", oldPath, "to", newPath, "status", status)`.

2021-05-10 19:50 UTC, Stebalien commented on core/corehttp/gateway_handler.go
> +		webError(w, "WritableGateway: parent is not a directory", errors.New("parent is not a directory"), http.StatusInternalServerError)
nit: stutter

```suggestion
		webError(w, "WritableGateway", errors.New("parent is not a directory"), http.StatusInternalServerError)
```

2021-05-10 19:50 UTC, Stebalien commented on core/corehttp/gateway_handler.go
> +		webError(w, "WritableGateway: empty path", errors.New("empty path"), http.StatusInternalServerError)
```suggestion
		webError(w, "WritableGateway", errors.New("empty path"), http.StatusInternalServerError)
```

2021-05-10 19:50 UTC, Stebalien commented on core/corehttp/gateway_handler.go
> +		webError(w, "WritableGateway: empty path", fmt.Errorf("empty path: %s", newPath), http.StatusBadRequest)
```suggestion
		webError(w, "WritableGateway", fmt.Errorf("empty path: %s", newPath), http.StatusBadRequest)
```

2021-05-10 19:50 UTC, Stebalien commented on core/corehttp/gateway_handler.go
> +		webError(w, "WritableGateway: target directory is not a directory", errors.New("target is not a directory"), http.StatusBadRequest)
```suggestion
		webError(w, "WritableGateway", errors.New("target is not a directory"), http.StatusBadRequest)
```

2021-05-10 19:50 UTC, Stebalien commented on core/corehttp/gateway_handler.go
> +		webError(w, "WritableGateway: empty path", fmt.Errorf("empty path: %s", newPath), http.StatusBadRequest)
```suggestion
		webError(w, "WritableGateway", fmt.Errorf("empty path: %s", newPath), http.StatusBadRequest)
```

2021-05-17 16:00 UTC, Stebalien commented
Please do use structered logging. E.g., `log.Debugw("redirected", "from", oldPath, "to", newPath, "status", status)`. We can't merge unless we either switch to this _or_ use `"%q"` when logging user-controlled strings (e.g., URLs). However, I'd _much_ prefer to use structured logging, so please do so.

2021-06-14 15:22 UTC, aschmahmann commented
@sujanasowrirajan when you get a chance to come back to this PR feel free to reopen, closing for now to help with tracking.

2021-06-14 15:22 UTC, closed without merging