feat: Swarm.EnableHolePunching by default
ipfs/go-ipfs pull request #8748
Opened 2022-02-22 13:47 UTC by lidel

- This PR changes the implicit default in ` Swarm.EnableHolePunching` to `true`.
  - Enables the  [Direct Connection Upgrade through Relay (DCUtR)](https://github.com/libp2p/specs/blob/master/relay/DCUtR.md) client (introduced in 0.11: https://github.com/ipfs/go-ipfs/pull/8562).

Ref. https://github.com/ipfs/go-ipfs/blob/master/docs/config.md#swarmenableholepunching

2022-02-25 05:44 UTC, marten-seemann requested changes
We don't have the relay discovery logic in libp2p yet. This PR should be blocked on that.

2022-03-01 03:03 UTC, BigLep commented
> We don't have the relay discovery logic in libp2p yet. This PR should be blocked on that.

@marten-seemann : is there a go-libp2p issue for this we can link to?

2022-04-11 12:40 UTC, Mitumaru approved these changes

2022-04-19 13:12 UTC, lidel commented
This PR needs https://github.com/ipfs/go-ipfs/pull/8868 to land first.

2022-04-27 23:19 UTC, lidel commented
Current status:  blocked by one go-libp2p@v0.19.0 bug
- `go test` and sharness `t0301-docker-migrate.sh` fail due to panic in migration code around IpfsFetcher caused by race condition around `go-libp2p@v0.19.0/p2p/protocol/holepunch/svc.go:150`
   - tracked in upstream bug:  https://github.com/libp2p/go-libp2p/issues/1448
      - fix:  https://github.com/libp2p/go-libp2p/pull/1467
      
This means we either need go-libp2p@v0.19.1 with the fix, or enabling hole punching needs to wait until 0.20.0.

2022-05-03 16:13 UTC, aschmahmann commented on core/node/libp2p/relay.go
> +				return
from standup: add an info log here noting that hole punching was silently turned off

2022-05-03 18:25 UTC, aschmahmann commented on core/node/libp2p/relay.go
> +					log.Info("HolePunching has been disabled due to the RelayClient being disabled.")
@lidel this comment was added per https://github.com/ipfs/go-ipfs/pull/8748/files#r863946425.

We're going to release the RC with this, but if you'd like to change the wording or have an objection to the logic we can revert during the RC process

2022-05-03 18:28 UTC, aschmahmann approved these changes

2022-05-03 19:20 UTC, merged